# -*- coding: utf-8 -*-
"""
Created on Tue Jun 30 14:46:13 2020

@author: Nathan
"""


def Function(x):
    return x*(x-1)

def Derivative(x, delta):
    df = (Function(x + delta) - Function(x))/delta
    return df
    
        
delta = 10e-2
x = 1.0

print("Derivative for large delta ", Derivative(x, delta))
# print(3602879701896397 / 2 ** 55) # LOL WTF https://docs.python.org/3/tutorial/floatingpoint.html


"""
We see that the solution generated by the computer does not agree entirely with the 
analytical solution. Analytically, df/dx with x = 1 is 1

"""

# Part B

print(Derivative(x, 10e-4), " for delta  = 10e-4")
print(Derivative(x, 10e-6), " for delta  = 10e-6")
print(Derivative(x, 10e-8), " for delta  = 10e-8")
print(Derivative(x, 10e-10), " for delta  = 10e-10")
print(Derivative(x, 10e-12), " for delta  = 10e-12")
print(Derivative(x, 10e-14), " for delta  = 10e-14")

"""
Notice the pattern of accuracy here. It improves then declines. 
"""